export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS_SUCCESS = 'RECEIVE_CONVERSATIONS_SUCCESS';
export const RECEIVE_CONVERSATIONS_FAILURE = 'RECEIVE_CONVERSATIONS_FAILURE';
export const REQUEST_CONVERSATION = 'REQUEST_CONVERSATION';
export const RECEIVE_CONVERSATION_SUCCESS = 'RECEIVE_CONVERSATION_SUCCESS';
export const RECEIVE_CONVERSATION_FAILURE = 'RECEIVE_CONVERSATION_FAILURE';
export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES_SUCCESS = 'RECEIVE_MESSAGES_SUCCESS';
export const RECEIVE_MESSAGES_FAILURE = 'RECEIVE_MESSAGES_FAILURE';
export const SEND_TYPING = 'SEND_TYPING';
export const STOP_TYPING = 'STOP_TYPING';
export const START_TYPING = 'START_TYPING';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const RECEIVE_TYPING = 'RECEIVE_TYPING';
export const REGISTER = 'REGISTER';
