export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';
export const FAILURE_CONVERSATIONS = 'FAILURE_CONVERSATIONS';

export const REQUEST_CONVERSATION = 'REQUEST_CONVERSATION';
export const RECEIVE_CONVERSATION = 'RECEIVE_CONVERSATION';
export const FAILURE_CONVERSATION = 'FAILURE_CONVERSATION';

export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const FAILURE_MESSAGES = 'FAILURE_MESSAGES';

export const START_TYPING = 'START_TYPING';
export const STOP_TYPING = 'STOP_TYPING';

export const SEND_TYPING = 'SEND_TYPING';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const REGISTER = 'REGISTER';
export const RECEIVE_TYPING = 'RECEIVE_TYPING';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const SEND_CODE = 'SEND_CODE';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';
export const SEND_CODE_FAILURE = 'SEND_CODE_FAILURE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
